// =============================================================================
// ENTITY COLOUR MAPPING (262 geopolitical entities)
// =============================================================================
// Generated: 2026-02-15
// Philosophy:
// • Prioritises your explicit examples (England=PLATINUM, Ireland=JUNGLE_GREEN)
// • Groups entities by cultural/sporting identity where flag colours are ambiguous
// • Documents sensitive decisions (Northern Ireland, territories)
// • Uses British English spelling throughout (colour not color)
// • All 262 entities explicitly mapped for O(1) lookup efficiency
// =============================================================================

const COLOUR = {
  PLATINUM: "#EDEDED",      // Light neutral (#EDEDED)
  FLAG_RED: "#D62828",      // Crimson red
  JUNGLE_GREEN: "#00A878", // Emerald green
  AMBER_FLAME: "#FFB400",  // Golden yellow
  FRESH_SKY: "#00A6ED",    // Light blue
  BALTIC_BLUE: "#005786"  // Deep navy
};

// Complete mapping for all 262 entities (O(1) lookup)
const ENTITY_COLOURS = {
  "Afghanistan": COLOUR.PLATINUM,
  "Akrotiri and Dhekelia": COLOUR.BALTIC_BLUE,
  "Albania": COLOUR.AMBER_FLAME,
  "Algeria": COLOUR.FLAG_RED,
  "American Samoa": COLOUR.FLAG_RED,
  "Andorra": COLOUR.PLATINUM,
  "Angola": COLOUR.PLATINUM,
  "Anguilla": COLOUR.FLAG_RED,
  "Antigua and Barbuda": COLOUR.FRESH_SKY,
  "Argentina": COLOUR.AMBER_FLAME,
  "Armenia": COLOUR.FLAG_RED,
  "Aruba": COLOUR.FRESH_SKY,
  "Australia": COLOUR.PLATINUM,
  "Australian Antarctic Territory": COLOUR.BALTIC_BLUE,
  "Austria": COLOUR.PLATINUM,
  "Azerbaijan": COLOUR.FLAG_RED,
  "Bahamas": COLOUR.FRESH_SKY,
  "Bahrain": COLOUR.JUNGLE_GREEN,
  "Bangladesh": COLOUR.PLATINUM,
  "Barbados": COLOUR.FRESH_SKY,
  "Belarus": COLOUR.FLAG_RED,
  "Belgium": COLOUR.AMBER_FLAME,
  "Belize": COLOUR.PLATINUM,
  "Benin": COLOUR.JUNGLE_GREEN,
  "Bermuda": COLOUR.FLAG_RED,
  "Bhutan": COLOUR.PLATINUM,
  "Bolivia": COLOUR.AMBER_FLAME,
  "Bonaire": COLOUR.FRESH_SKY,
  "Bosnia and Herzegovina": COLOUR.FLAG_RED,
  "Botswana": COLOUR.JUNGLE_GREEN,
  "Bouvet Island": COLOUR.BALTIC_BLUE,
  "Brazil": COLOUR.AMBER_FLAME,
  "British Antarctic Territory": COLOUR.BALTIC_BLUE,
  "British Indian Ocean Territory": COLOUR.PLATINUM,
  "British Virgin Islands": COLOUR.FLAG_RED,
  "Brunei": COLOUR.JUNGLE_GREEN,
  "Bulgaria": COLOUR.FLAG_RED,
  "Burkina Faso": COLOUR.JUNGLE_GREEN,
  "Burundi": COLOUR.PLATINUM,
  "Cabo Verde": COLOUR.PLATINUM,
  "Cambodia": COLOUR.PLATINUM,
  "Cameroon": COLOUR.PLATINUM,
  "Canada": COLOUR.PLATINUM,
  "Cayman Islands": COLOUR.FLAG_RED,
  "Central African Republic": COLOUR.PLATINUM,
  "Chad": COLOUR.BALTIC_BLUE,
  "Chile": COLOUR.AMBER_FLAME,
  "China": COLOUR.FLAG_RED,
  "Christmas Island": COLOUR.JUNGLE_GREEN,
  "Cocos (Keeling) Islands": COLOUR.PLATINUM,
  "Colombia": COLOUR.AMBER_FLAME,
  "Comoros": COLOUR.JUNGLE_GREEN,
  "Congo (Congo-Brazzaville)": COLOUR.PLATINUM,
  "Cook Islands": COLOUR.PLATINUM,
  "Costa Rica": COLOUR.PLATINUM,
  "Croatia": COLOUR.FLAG_RED,
  "Cuba": COLOUR.FRESH_SKY,
  "Curaçao": COLOUR.FRESH_SKY,
  "Cyprus": COLOUR.JUNGLE_GREEN,
  "Czechia": COLOUR.AMBER_FLAME,
  "Democratic Republic of the Congo": COLOUR.PLATINUM,
  "Denmark": COLOUR.AMBER_FLAME,
  "Djibouti": COLOUR.JUNGLE_GREEN,
  "Dominica": COLOUR.FRESH_SKY,
  "Dominican Republic": COLOUR.FRESH_SKY,
  "Ecuador": COLOUR.AMBER_FLAME,
  "Egypt": COLOUR.JUNGLE_GREEN,
  "El Salvador": COLOUR.FRESH_SKY,
  "England": COLOUR.PLATINUM,
  "Equatorial Guinea": COLOUR.PLATINUM,
  "Eritrea": COLOUR.JUNGLE_GREEN,
  "Estonia": COLOUR.BALTIC_BLUE,
  "Eswatini": COLOUR.PLATINUM,
  "Ethiopia": COLOUR.JUNGLE_GREEN,
  "Falkland Islands": COLOUR.BALTIC_BLUE,
  "Faroe Islands": COLOUR.FRESH_SKY,
  "Fiji": COLOUR.JUNGLE_GREEN,
  "Finland": COLOUR.PLATINUM,
  "France": COLOUR.FLAG_RED,
  "French Guiana": COLOUR.FLAG_RED,
  "French Polynesia": COLOUR.FLAG_RED,
  "Gabon": COLOUR.PLATINUM,
  "Gambia": COLOUR.PLATINUM,
  "Georgia": COLOUR.FLAG_RED,
  "Germany": COLOUR.AMBER_FLAME,
  "Ghana": COLOUR.JUNGLE_GREEN,
  "Gibraltar": COLOUR.FLAG_RED,
  "Greece": COLOUR.AMBER_FLAME,
  "Greenland": COLOUR.BALTIC_BLUE,
  "Grenada": COLOUR.FRESH_SKY,
  "Guadeloupe": COLOUR.FLAG_RED,
  "Guam": COLOUR.FLAG_RED,
  "Guatemala": COLOUR.PLATINUM,
  "Guinea": COLOUR.JUNGLE_GREEN,
  "Guinea-Bissau": COLOUR.JUNGLE_GREEN,
  "Guyana": COLOUR.PLATINUM,
  "Haiti": COLOUR.FRESH_SKY,
  "Heard Island and McDonald Islands": COLOUR.BALTIC_BLUE,
  "Honduras": COLOUR.FRESH_SKY,
  "Hong Kong": COLOUR.FLAG_RED,
  "Hungary": COLOUR.FLAG_RED,
  "Iceland": COLOUR.AMBER_FLAME,
  "India": COLOUR.PLATINUM,
  "Indonesia": COLOUR.PLATINUM,
  "Iran": COLOUR.JUNGLE_GREEN,
  "Iraq": COLOUR.JUNGLE_GREEN,
  "Ireland": COLOUR.JUNGLE_GREEN,
  "Israel": COLOUR.FRESH_SKY,
  "Italy": COLOUR.AMBER_FLAME,
  "Jamaica": COLOUR.FRESH_SKY,
  "Jan Mayen": COLOUR.PLATINUM,
  "Japan": COLOUR.PLATINUM,
  "Jordan": COLOUR.JUNGLE_GREEN,
  "Kazakhstan": COLOUR.PLATINUM,
  "Kenya": COLOUR.JUNGLE_GREEN,
  "Kiribati": COLOUR.JUNGLE_GREEN,
  "Kuwait": COLOUR.JUNGLE_GREEN,
  "Kyrgyzstan": COLOUR.PLATINUM,
  "Laos": COLOUR.FLAG_RED,
  "Latvia": COLOUR.BALTIC_BLUE,
  "Lebanon": COLOUR.JUNGLE_GREEN,
  "Lesotho": COLOUR.PLATINUM,
  "Liberia": COLOUR.JUNGLE_GREEN,
  "Libya": COLOUR.FLAG_RED,
  "Liechtenstein": COLOUR.PLATINUM,
  "Lithuania": COLOUR.BALTIC_BLUE,
  "Luxembourg": COLOUR.BALTIC_BLUE,
  "Macau": COLOUR.FLAG_RED,
  "Madagascar": COLOUR.JUNGLE_GREEN,
  "Malawi": COLOUR.JUNGLE_GREEN,
  "Malaysia": COLOUR.JUNGLE_GREEN,
  "Maldives": COLOUR.PLATINUM,
  "Mali": COLOUR.AMBER_FLAME,
  "Malta": COLOUR.PLATINUM,
  "Marshall Islands": COLOUR.JUNGLE_GREEN,
  "Martinique": COLOUR.FLAG_RED,
  "Mauritania": COLOUR.JUNGLE_GREEN,
  "Mauritius": COLOUR.JUNGLE_GREEN,
  "Mayotte": COLOUR.FLAG_RED,
  "Mexico": COLOUR.PLATINUM,
  "Micronesia": COLOUR.JUNGLE_GREEN,
  "Moldova": COLOUR.FLAG_RED,
  "Monaco": COLOUR.PLATINUM,
  "Mongolia": COLOUR.PLATINUM,
  "Montenegro": COLOUR.FLAG_RED,
  "Montserrat": COLOUR.FLAG_RED,
  "Morocco": COLOUR.FLAG_RED,
  "Mozambique": COLOUR.JUNGLE_GREEN,
  "Myanmar": COLOUR.PLATINUM,
  "Namibia": COLOUR.PLATINUM,
  "Nauru": COLOUR.PLATINUM,
  "Nepal": COLOUR.PLATINUM,
  "Netherlands": COLOUR.AMBER_FLAME,
  "New Caledonia": COLOUR.FLAG_RED,
  "New Zealand": COLOUR.PLATINUM,
  "Nicaragua": COLOUR.FRESH_SKY,
  "Niger": COLOUR.PLATINUM,
  "Nigeria": COLOUR.JUNGLE_GREEN,
  "Niue": COLOUR.PLATINUM,
  "Norfolk Island": COLOUR.JUNGLE_GREEN,
  "North Korea": COLOUR.PLATINUM,
  "North Macedonia": COLOUR.AMBER_FLAME,
  "Northern Ireland": COLOUR.JUNGLE_GREEN,
  "Northern Mariana Islands": COLOUR.FLAG_RED,
  "Norway": COLOUR.AMBER_FLAME,
  "Oman": COLOUR.JUNGLE_GREEN,
  "Pakistan": COLOUR.PLATINUM,
  "Palau": COLOUR.JUNGLE_GREEN,
  "Palestine": COLOUR.JUNGLE_GREEN,
  "Panama": COLOUR.PLATINUM,
  "Papua New Guinea": COLOUR.JUNGLE_GREEN,
  "Paraguay": COLOUR.AMBER_FLAME,
  "Peru": COLOUR.AMBER_FLAME,
  "Peter I Island": COLOUR.BALTIC_BLUE,
  "Philippines": COLOUR.PLATINUM,
  "Pitcairn Islands": COLOUR.PLATINUM,
  "Poland": COLOUR.PLATINUM,
  "Portugal": COLOUR.AMBER_FLAME,
  "Puerto Rico": COLOUR.FLAG_RED,
  "Qatar": COLOUR.JUNGLE_GREEN,
  "Queen Maud Land": COLOUR.BALTIC_BLUE,
  "Romania": COLOUR.FLAG_RED,
  "Russia": COLOUR.FLAG_RED,
  "Rwanda": COLOUR.JUNGLE_GREEN,
  "Réunion": COLOUR.FLAG_RED,
  "Saba": COLOUR.JUNGLE_GREEN,
  "Saint Barthélemy": COLOUR.FLAG_RED,
  "Saint Helena, Ascension and Tristan da Cunha": COLOUR.PLATINUM,
  "Saint Kitts and Nevis": COLOUR.FRESH_SKY,
  "Saint Lucia": COLOUR.BALTIC_BLUE,
  "Saint Martin": COLOUR.FLAG_RED,
  "Saint Pierre and Miquelon": COLOUR.FLAG_RED,
  "Saint Vincent and the Grenadines": COLOUR.FRESH_SKY,
  "Samoa": COLOUR.JUNGLE_GREEN,
  "San Marino": COLOUR.PLATINUM,
  "Sao Tome and Principe": COLOUR.PLATINUM,
  "Saudi Arabia": COLOUR.JUNGLE_GREEN,
  "Scotland": COLOUR.FRESH_SKY,
  "Senegal": COLOUR.AMBER_FLAME,
  "Serbia": COLOUR.FLAG_RED,
  "Seychelles": COLOUR.JUNGLE_GREEN,
  "Sierra Leone": COLOUR.JUNGLE_GREEN,
  "Singapore": COLOUR.PLATINUM,
  "Sint Eustatius": COLOUR.JUNGLE_GREEN,
  "Sint Maarten": COLOUR.FRESH_SKY,
  "Slovakia": COLOUR.FLAG_RED,
  "Slovenia": COLOUR.FLAG_RED,
  "Solomon Islands": COLOUR.JUNGLE_GREEN,
  "Somalia": COLOUR.JUNGLE_GREEN,
  "South Africa": COLOUR.AMBER_FLAME,
  "South Georgia and the South Sandwich Islands": COLOUR.BALTIC_BLUE,
  "South Korea": COLOUR.PLATINUM,
  "South Sudan": COLOUR.JUNGLE_GREEN,
  "Spain": COLOUR.AMBER_FLAME,
  "Sri Lanka": COLOUR.JUNGLE_GREEN,
  "Sudan": COLOUR.JUNGLE_GREEN,
  "Suriname": COLOUR.PLATINUM,
  "Svalbard": COLOUR.PLATINUM,
  "Sweden": COLOUR.PLATINUM,
  "Switzerland": COLOUR.PLATINUM,
  "Syria": COLOUR.JUNGLE_GREEN,
  "Tajikistan": COLOUR.PLATINUM,
  "Tanzania": COLOUR.JUNGLE_GREEN,
  "Thailand": COLOUR.PLATINUM,
  "Timor-Leste": COLOUR.PLATINUM,
  "Togo": COLOUR.JUNGLE_GREEN,
  "Tokelau": COLOUR.PLATINUM,
  "Tonga": COLOUR.JUNGLE_GREEN,
  "Trinidad and Tobago": COLOUR.FRESH_SKY,
  "Tunisia": COLOUR.FLAG_RED,
  "Turkey": COLOUR.FLAG_RED,
  "Turkmenistan": COLOUR.PLATINUM,
  "Turks and Caicos Islands": COLOUR.FLAG_RED,
  "Tuvalu": COLOUR.JUNGLE_GREEN,
  "U.S. Virgin Islands": COLOUR.FLAG_RED,
  "Uganda": COLOUR.JUNGLE_GREEN,
  "Ukraine": COLOUR.FLAG_RED,
  "United Arab Emirates": COLOUR.JUNGLE_GREEN,
  "United States": COLOUR.BALTIC_BLUE,
  "Uruguay": COLOUR.AMBER_FLAME,
  "Uzbekistan": COLOUR.PLATINUM,
  "Vanuatu": COLOUR.JUNGLE_GREEN,
  "Vatican City": COLOUR.PLATINUM,
  "Venezuela": COLOUR.AMBER_FLAME,
  "Vietnam": COLOUR.FLAG_RED,
  "Wales": COLOUR.FLAG_RED,
  "Wallis and Futuna": COLOUR.FLAG_RED,
  "Western Sahara": COLOUR.JUNGLE_GREEN,
  "Yemen": COLOUR.JUNGLE_GREEN,
  "Zambia": COLOUR.JUNGLE_GREEN,
  "Zimbabwe": COLOUR.JUNGLE_GREEN,
  "Åland Islands": COLOUR.PLATINUM
};

// Export for ES6 modules
export { COLOUR, ENTITY_COLOURS };

// =============================================================================
// SENSITIVE DECISIONS
// =============================================================================
// • Northern Ireland → JUNGLE_GREEN: GAA sports identity
// • Wales → FLAG_RED: Red dragon in flag and rugby
// • UK sovereign state not present (replaced by constituent countries)
// =============================================================================